name: Validate and Create Pull Request

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build Project
        run: npm run build -- --configuration=production

  create_pull_request:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}  # Utilizando o GITHUB_TOKEN padrão
          commit-message: "Auto-generated PR from develop to main"
          branch: main  # Branch de destino
          base: develop    # Certifique-se que `main` é a branch base
          title: "Sync develop with main"
          body: "Este PR foi criado automaticamente para sincronizar as mudanças da develop com a main."
          assignees: ''  # Pode adicionar responsáveis automaticamente
          reviewers: 'cleiton016'  # Pode adicionar revisores automaticamente
